name: linux
on: [push, pull_request]
jobs:
  test:
    name: ${{ matrix.vi }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vi: [neovim, vim]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: thinca/vim-themis
          path: vim-themis
      - name: Install ${{ matrix.vi }}
        run: brew install ${{ matrix.vi }}
      - name: Run tests
        env:
          THEMIS_VIM: ${{ (matrix.vi == 'neovim' && 'nvim') || 'vim' }}
        run: ./vim-themis/bin/themis ./test/test.vim
