name: test
on: [push, pull_request]
jobs:
  test:
    name: runner / test
    runs-on: ${{ matrix.os  }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        vi: [neovim, vim]
    steps:
      - uses: actions/checkout@v2
      - name: Install ${{ matrix.vi }}
        run: brew install ${{ matrix.vi }}
      - name: Run test
        run: ./test/${{ matrix.vi }}.sh
